#!/bin/sh
set -e

reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (1)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 1 --episode-title "Overlooking View"               "俯瞰風景"       --episode-total 7 --studio "ufotable" "ufotable" --director "Ei Aoki"           "あおきえい" --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2007 12  1 --subber "Pretentious"         -- '[ANE] Kara no Kyoukai - 1 - Overlooking View [BDRip 1080p x264 FLAC].mkv'              "Kara no Kyoukai (1).mkv"
reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (2)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 2 --episode-title "A Study in Murder - Part 1"     "殺人考察（前）" --episode-total 7 --studio "ufotable" "ufotable" --director "Takuya Nonaka"     "野中卓也"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2007 12 29 --subber "Pretentious"         -- '[ANE] Kara no Kyoukai - 2 - Murder Speculation (Part A) [BDRip 1080p x264 FLAC].mkv'   "Kara no Kyoukai (2).mkv"
reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (3)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 3 --episode-title "Remaining Sense of Pain"        "痛覚残留"       --episode-total 7 --studio "ufotable" "ufotable" --director "Mitsuru Okunai"    "小船井充"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2008  2  9 --subber "Pretentious"         -- '[ANE] Kara no Kyoukai - 3 - Remaining Sense of Pain [BDRip 1080p x264 FLAC].mkv'       "Kara no Kyoukai (3).mkv"
reanimate -g 8 -2 1 -m -l ja ja en en -T "Kara no Kyoukai (4)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 4 --episode-title "The Hollow Shrine"              "伽藍の洞"       --episode-total 7 --studio "ufotable" "ufotable" --director "Teiichi Takiguchi" "滝口禎一"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2008  5 24 --subber "gg-TakaJun" "Retail" -- '[ANE] Kara no Kyoukai - 4v0 - The Hollow Shrine [BDRip 1080p x264 FLAC].mkv'           "Kara no Kyoukai (4).mkv"
reanimate -g 8 -2 1 -m -l ja ja en en -T "Kara no Kyoukai (5)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 5 --episode-title "Paradox Spiral"                 "矛盾螺旋"       --episode-total 7 --studio "ufotable" "ufotable" --director "Takayuki Hirao"    "平尾隆之"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2008  8 16 --subber "gg-TakaJun" "Retail" -- '[ANE] Kara no Kyoukai - 5v0 - Paradox Paradigm [BDRip 1080p x264 FLAC].mkv'            "Kara no Kyoukai (5).mkv"
reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (6)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 6 --episode-title "Oblivion Recording"             "忘却録音"       --episode-total 7 --studio "ufotable" "ufotable" --director "Takahiro Miura"    "三浦貴博"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2008 12 20 --subber "Pretentious"         -- '[ANE] Kara no Kyoukai - 6 - Oblivion Recording [BDRip 1080p x264 FLAC].mkv'            "Kara no Kyoukai (6).mkv"
reanimate -g 8 -2 1 -m -l ja ja en en -T "Kara no Kyoukai (7)"        -L en ja --title "The Garden of Sinners" "空の境界" --episode 7 --episode-title "A Study in Murder - Part 2"     "殺人考察（後）" --episode-total 7 --studio "ufotable" "ufotable" --director "Shinsuke Takizawa" "瀧沢進介"   --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2009  8  8 --subber "gg-TakaJun" "Retail" -- '[ANE] Kara no Kyoukai - 7v0 - Murder Speculation (Part B) [BDRip 1080p x264 FLAC].mkv' "Kara no Kyoukai (7).mkv"
reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (Epilogue)" -L en ja --title "The Garden of Sinners" "空の境界"             --episode-title "Epilogue"                       "終章"                             --studio "ufotable" "ufotable" --director "Hikaru Kondo"      "近藤光"     --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2010 12 18 --subber "66"                  -- '[ANE] Kara no Kyoukai - Epilogue [BDRip 1080p x264 FLAC].mkv'                          "Kara no Kyoukai (Epilogue).mkv"
reanimate -g 8 -2 1 -m -l ja ja en    -T "Kara no Kyoukai (Remix)"    -L en ja --title "The Garden of Sinners" "空の境界"             --episode-title "Remix -Gate of Seventh Heaven-" "Remix -Gate of seventh heaven-"   --studio "ufotable" "ufotable" --director "Yuuichi Terao, Sae Yoshikawa, Hikaru Kondou" "寺尾優一、吉川冴、近藤光" --screenplay "Masaki Hiramatsu" "平松正樹" --release-date 2009  3 14 --subber "Retail" -- '[ANE] Kara no Kyoukai - Remix v0 - Gate of Seventh Heaven [BDRip 1080p x264 FLAC].mkv' "Kara no Kyoukai (Remix).mkv"

reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (1)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 1 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2007 12  1 --subber "Pretentious"     -- '[ANE] Kara no Kyoukai - Cinema Intro 1 [BDRip 1080p x264 FLAC].mkv'   "Kara no Kyoukai Intro (1).mkv" 
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (2)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 2 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2007 12 29 --subber "Pretentious"     -- '[ANE] Kara no Kyoukai - Cinema Intro 2 [BDRip 1080p x264 FLAC].mkv'   "Kara no Kyoukai Intro (2).mkv"
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (3)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 3 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2008  2  9 --subber "Pretentious"     -- '[ANE] Kara no Kyoukai - Cinema Intro 3 [BDRip 1080p x264 FLAC].mkv'   "Kara no Kyoukai Intro (3).mkv"
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (4)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 4 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2008  5 24 --subber "gg-TakaJun, CGi" -- '[ANE] Kara no Kyoukai - Cinema Intro 4v0 [BDRip 1080p x264 FLAC].mkv' "Kara no Kyoukai Intro (4).mkv"
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (5)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 5 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2008  8 16 --subber "gg-TakaJun, CGi" -- '[ANE] Kara no Kyoukai - Cinema Intro 5v0 [BDRip 1080p x264 FLAC].mkv' "Kara no Kyoukai Intro (5).mkv"
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (6)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 6 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2008 12 20 --subber "Pretentious"     -- '[ANE] Kara no Kyoukai - Cinema Intro 6 [BDRip 1080p x264 FLAC].mkv'   "Kara no Kyoukai Intro (6).mkv"
reanimate -g 8 -2 1 -m -l ja ja en -T "Kara no Kyoukai Intro (7)" -L en ja --title "The Garden of Sinners" "空の境界" --episode 7 --episode-total 7 --studio "ufotable" "ufotable" --release-date 2009  8  8 --subber "gg-TakaJun, CGi" -- '[ANE] Kara no Kyoukai - Cinema Intro 7v0 [BDRip 1080p x264 FLAC].mkv' "Kara no Kyoukai Intro (7).mkv"
